# .streamlit/secrets.toml

[gcp_service_account]
type = "service_account"
project_id = "maia-analyzer"
private_key_id = "64779a7c79b1f668556c0b1b29a06c16622c1572"
# A chave privada é colada aqui no formato multi-linha (mantendo as quebras de linha)
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC2pbNLWiG+ChFc
fYjp8MgdQawgYB5qhNu0vkoNlBPd1/8aWytjUDSLydWuNK+fyH0uOaM8IaarBu40
jbHeKDMEBnHjQlv2idjp2fZ/UcSwbgoVQOmSadkotc2zH+L/sX7/s/UnLPvjeMtB
Wvx5om4qIixdIRopczQ1sUbgNWXPimaOPl/b1xQkbOjh6S1fARfLDt5lCEQSnO6e
mLn2pw5Dqazq/FPJGwtxju/q79rSuWRfBBckEgtPRpxT8rR5Z8vReq3hfwSXiLK6
AYhfvwx6ejN7yBEa/2C7600dlqtyZBmDZ1MGooZjRD0xzLZoJhPB4HQJx9Tf4LlU
+H5wKx9lAgMBAAECggEAQDCm/RX9otTV+ivySMmDAuk4LZ6qQeRUdMalrvT6MG6/
bItbCcm/1dsG2nUQvfaPrAW8rR7kfNnwMI8V0k5Nc54yO1zwhgo3LiSYoXFiz2C0
8XhBPmAt3kVauBe+Rv+h8wrTX0PLeMvUnzDzZ2ojDnK5JbfDAotG75HQp26My+2u
c3pXW9Xx6LSoPZJP2jI30N4klpywKOW52Ah0H5sLyQrGa/Z7hw9i1y8r2cDUh5ak
+HHDfFyV2KWOGAenE7W2GI04fg+sOhXZmeXEti1z+7kc1n5zLKbPJO7lnVtUq07U
ZurbVja72fI68UCGfsx+1WHTqGbrauvQG9ei9GhWpwKBgQD0QOQzmWNcXbhfctO8
vk90yD864YhLCzpmVVAfNG3kHkOACsVKeTbvgmeGf6xzicmtQ8lt71KCdAQZIVGS
xJYFkwUnWdB72VQRu6uKXmG0zKCpoh/pMT7DDltTLE0zZEM6yQ3OsSoDvXW7UptW
XsVj3dJEJnjCLYEPM92CHwa0SwKBgQC/blk/Is+BktOUtQ++l4YBeV9TKwMws5p0
FRXlu4Cn4WdyxhL/OZiKiqj1iaS1s0IJLTGJWvtoRtFx+uiWSk3EVE6fm3Vmt8qh
ldvhB6MV7CK5BRtQUc8F2/RvsGwKgcKv4dT1uFGdFm5qiWM0jV19eGEz2QhOvBi1
MqcgwCRNDwKBgQDEhq3WYpWSzQm7Ks348HtH8JMHkk2ya99aVUx5PxsoT71p+cCS
UoOEJL2dd37PG898rK0W2lfeBPEDM07KM4iuBYRBDD/2VoARIJo+ZABjk721n2/j
li70jMmoW13mesapNvn4E45FohxnU2kPDoPt/Z3gHcBOJITSMZ4Jw2MGjwKBgQC9
Xa2PVSIsLVB75HiEs2NuheAUZ5IqVSDPACS/MzJb4A/za5lTPGh3dB8bdWOoEoGa
jkhYddYJGzUJKYl3Ul2Hf1afcKs8R0d9fL8b5fAgOY1HtZOFasf+Jc2xxrW51w79
6co+oGyrlor3fJzUWZtICRMutN0Q9eUDKe5F6Yx/ZQKBgQCLackSAURbyfXpcqB0
0B4xpxulUiiBSpiyJUhNgGVFIi5W8OuKQgFuDhQM9qlcHnTLkGCSRhn1OaKJOXuw
W90GCZJqlJ+XRuDamrq1e7NH5eQH85fC4Xd+jpe7BBeXFLxBBITeKp8WrclrAHy5
VyYEpvXCZEkLzRay90PwltIjyg==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-etl@maia-analyzer.iam.gserviceaccount.com"
client_id = "101156388841214668286"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-etl%40maia-analyzer.iam.gserviceaccount.com"
universe_domain = "googleapis.com" 

[google_sheets]
planilha_id = "1g6lnrB-N4kgrbEiZKEYaoll4la9TnfBJh4VvioqbC78" # 📌 SUBSTITUA ESTE VALOR PELO ID DA SUA PLANILHA
